import pandas as pd

REQUIRED_COLUMNS = [
    "invoice_number",
    "invoice_date",  # bill date; must parse as YYYY-MM-DD, DD-MM-YYYY, or DD/MM/YYYY
    "seller_gstin",
    "seller_state",
    "realization_from_invoice",  # total item value, tax-inclusive
    "tax_rate",  # combined GST rate as a percentage, e.g. 18 for a 9+9 CGST/SGST split or 18 IGST
    "quantity",
    "hsn_code",
    "awb_number",  # Air-waybill number, posted to the bill's "AWB Number" field
]

EWAY_BILL_MAPPING_REQUIRED_COLUMNS = ["invoice_number", "eway_bill_number"]

# Column mapping for the Amazon Liquidator manifest CSV format (e.g.
# LIQUIDATOR-<code>-LIQUIDATOR-<uuid>.csv), keyed by each source column's
# name after the same normalization applied below (lowercased, spaces -> _).
# tax_rate isn't a 1:1 rename -- it's derived from cgst_rate+sgst_rate or
# igst_rate (whichever is populated for that row) since the manifest doesn't
# carry a single combined-rate column.
LIQUIDATOR_MANIFEST_COLUMN_MAP = {
    "invoice_no.": "invoice_number",
    "tax_invoice_date": "invoice_date",
    "source_gstin": "seller_gstin",
    "ship_from_state": "seller_state",
    "realization_value_calculated_in_invoice_(reference_value_multiplied_by_vrr%)": "realization_from_invoice",
    "product_title/description": "description",
    "transaction_id_(air-waybill_number_in_manifest)": "awb_number",
}

# Header tokens (post-normalization) used to locate the real header row in a
# "Classic Export"-style workbook, where the target sheet is called "Data"
# and the first row is blank/aggregate junk above the actual headers.
_LIQUIDATOR_HEADER_TOKENS = {"invoice_no.", "source_gstin", "ship_from_state", "hsn_code"}

# Column mapping for the "EWB generated by others Validation" workbook
# (one sheet per state, e.g. Telangana/Maharashtra/Karnataka), keyed by
# normalized source column name.
EWB_VALIDATION_COLUMN_MAP = {
    "doc_no": "invoice_number",
    "ewb.no": "eway_bill_number",
}


def _format_integer_string(value):
    """Formats a large integer-looking value (HSN code, AWB number, E-way
    Bill number, ...) as a plain digit string, not pandas' default float
    repr (e.g. "1211222253776.0"), which happens whenever the source column
    has any blank cell (forcing pandas to infer float64 for the whole
    column). These values are compared/sent as exact strings downstream
    (Zoho's hsn_or_sac, the E-way Bill API's EWB number, ...), so a stray
    ".0" silently breaks every match/request."""
    if pd.isna(value):
        return ""
    try:
        return str(int(float(value)))
    except (TypeError, ValueError):
        return str(value).strip()


def _normalize_columns(df: pd.DataFrame) -> pd.DataFrame:
    df.columns = [str(c).strip().lower().replace(" ", "_") for c in df.columns]
    return df


def _read_table(file) -> pd.DataFrame:
    """Reads an uploaded excel (.xlsx/.xls) or .csv file into a DataFrame,
    auto-detecting the real header row/sheet for a "Classic Export"-style
    workbook (a "Data" sheet with a blank/junk first row above the headers,
    alongside an unrelated pivot-summary sheet)."""
    name = getattr(file, "name", str(file))
    if name.lower().endswith(".csv"):
        return pd.read_csv(file)

    xl = pd.ExcelFile(file)
    sheet_name = next((s for s in xl.sheet_names if s.strip().lower() == "data"), xl.sheet_names[0])

    preview = xl.parse(sheet_name, header=None, nrows=10)
    header_row = 0
    for i, row in preview.iterrows():
        cells = {str(v).strip().lower().replace(" ", "_") for v in row.tolist()}
        if len(_LIQUIDATOR_HEADER_TOKENS & cells) >= 2:
            header_row = i
            break

    return xl.parse(sheet_name, header=header_row)


def _read_all_sheets(file) -> pd.DataFrame:
    """Reads and concatenates every non-empty sheet in an uploaded excel/csv
    file -- used for workbooks split one-sheet-per-state (e.g. the E-way
    Bill validation workbook: Telangana/Maharashtra/Karnataka)."""
    name = getattr(file, "name", str(file))
    if name.lower().endswith(".csv"):
        return pd.read_csv(file)

    xl = pd.ExcelFile(file)
    frames = [xl.parse(sheet) for sheet in xl.sheet_names]
    frames = [f for f in frames if not f.empty]
    if not frames:
        return pd.DataFrame()
    return pd.concat(frames, ignore_index=True)


def _apply_liquidator_manifest_mapping(df: pd.DataFrame) -> pd.DataFrame:
    """If this looks like the Amazon Liquidator manifest format (detected by
    its distinctive source_gstin/invoice_no. columns rather than our own
    invoice_number/seller_gstin), remap its columns onto our schema and
    derive tax_rate from cgst_rate+sgst_rate or igst_rate."""
    if "invoice_number" in df.columns or "source_gstin" not in df.columns:
        return df

    df = df.rename(columns=LIQUIDATOR_MANIFEST_COLUMN_MAP)
    # cgst_rate/sgst_rate/igst_rate can come in as either a plain percentage
    # (9.0 meaning 9%) or a fraction (0.09 meaning 9%), depending on the
    # export. A real GST slab is never between 0 and 1 as a percentage (the
    # slabs are 0/0.25/3/5/12/18/28), so any value in that range is
    # unambiguously a fraction and gets scaled up; anything >= 1 is already
    # a percentage and is left as-is.
    def _as_percentage(rate_column):
        rate_column = rate_column.fillna(0)
        return rate_column.where(~((rate_column > 0) & (rate_column < 1)), rate_column * 100)

    df["tax_rate"] = _as_percentage(df["cgst_rate"]) + _as_percentage(df["sgst_rate"]) + _as_percentage(df["igst_rate"])
    return df


def _apply_ewb_validation_mapping(df: pd.DataFrame) -> pd.DataFrame:
    """If this looks like the "EWB generated by others Validation" workbook
    (detected by its distinctive doc_no/ewb.no columns), remap onto our
    invoice_number/eway_bill_number schema."""
    if "invoice_number" in df.columns or "doc_no" not in df.columns or "ewb.no" not in df.columns:
        return df
    return df.rename(columns=EWB_VALIDATION_COLUMN_MAP)


def parse_invoice_sheet(file) -> pd.DataFrame:
    df = _read_table(file)
    df = _normalize_columns(df)
    df = _apply_liquidator_manifest_mapping(df)

    missing = [c for c in REQUIRED_COLUMNS if c not in df.columns]
    if missing:
        raise ValueError(f"Excel is missing required columns: {missing}")

    df["invoice_number"] = df["invoice_number"].astype(str).str.strip()

    df["awb_number"] = df["awb_number"].apply(_format_integer_string)
    df["hsn_code"] = df["hsn_code"].apply(_format_integer_string)

    parsed_dates = pd.to_datetime(df["invoice_date"], dayfirst=True, errors="coerce")
    if parsed_dates.isna().any():
        bad_rows = df.loc[parsed_dates.isna(), "invoice_number"].tolist()
        raise ValueError(f"Excel has unparseable invoice_date values for invoice_number(s): {bad_rows}")
    df["invoice_date"] = parsed_dates.dt.strftime("%Y-%m-%d")

    # realization_from_invoice is tax-inclusive; back out the taxable (base) amount
    # from the combined GST rate -- e.g. realization 336.40 at 18% -> taxable 285.08.
    df["taxable_amount"] = df["realization_from_invoice"] / (1 + df["tax_rate"] / 100)
    df["tax_amount"] = df["realization_from_invoice"] - df["taxable_amount"]

    return df


def parse_eway_bill_mapping(file) -> dict[str, str]:
    """Parses the second excel (invoice_number -> eway_bill_number) into a dict.
    An invoice_number with no entry here is a distinct failure from one whose
    E-way Bill number is present but fails the E-way Bill API lookup."""
    df = _read_all_sheets(file)
    df = _normalize_columns(df)
    df = _apply_ewb_validation_mapping(df)

    missing = [c for c in EWAY_BILL_MAPPING_REQUIRED_COLUMNS if c not in df.columns]
    if missing:
        raise ValueError(f"E-way Bill mapping excel is missing required columns: {missing}")

    df = df.dropna(subset=["invoice_number", "eway_bill_number"])
    df["invoice_number"] = df["invoice_number"].astype(str).str.strip()
    df["eway_bill_number"] = df["eway_bill_number"].apply(_format_integer_string)
    return dict(zip(df["invoice_number"], df["eway_bill_number"]))
